/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CarSafetyRouteImport } from './routes/car-safety'
import { Route as AlfabyteRouteImport } from './routes/alfabyte'
import { Route as AiVisionRouteImport } from './routes/ai-vision'
import { Route as IndexRouteImport } from './routes/index'

const CarSafetyRoute = CarSafetyRouteImport.update({
  id: '/car-safety',
  path: '/car-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const AlfabyteRoute = AlfabyteRouteImport.update({
  id: '/alfabyte',
  path: '/alfabyte',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVisionRoute = AiVisionRouteImport.update({
  id: '/ai-vision',
  path: '/ai-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-vision': typeof AiVisionRoute
  '/alfabyte': typeof AlfabyteRoute
  '/car-safety': typeof CarSafetyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-vision': typeof AiVisionRoute
  '/alfabyte': typeof AlfabyteRoute
  '/car-safety': typeof CarSafetyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-vision': typeof AiVisionRoute
  '/alfabyte': typeof AlfabyteRoute
  '/car-safety': typeof CarSafetyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-vision'
    | '/alfabyte'
    | '/car-safety'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-vision'
    | '/alfabyte'
    | '/car-safety'
  id:
    | '__root__'
    | '/'
    | '/ai-vision'
    | '/alfabyte'
    | '/car-safety'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiVisionRoute: typeof AiVisionRoute
  AlfabyteRoute: typeof AlfabyteRoute
  CarSafetyRoute: typeof CarSafetyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/car-safety': {
      id: '/car-safety'
      path: '/car-safety'
      fullPath: '/car-safety'
      preLoaderRoute: typeof CarSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alfabyte': {
      id: '/alfabyte'
      path: '/alfabyte'
      fullPath: '/alfabyte'
      preLoaderRoute: typeof AlfabyteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-vision': {
      id: '/ai-vision'
      path: '/ai-vision'
      fullPath: '/ai-vision'
      preLoaderRoute: typeof AiVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiVisionRoute: AiVisionRoute,
  AlfabyteRoute: AlfabyteRoute,
  CarSafetyRoute: CarSafetyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
