/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as CarSafetyRouteImport } from './routes/car-safety'
import { Route as AlfabyteRouteImport } from './routes/alfabyte'
import { Route as AiVisionRouteImport } from './routes/ai-vision'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const CarSafetyRoute = CarSafetyRouteImport.update({
  id: '/car-safety',
  path: '/car-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const AlfabyteRoute = AlfabyteRouteImport.update({
  id: '/alfabyte',
  path: '/alfabyte',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVisionRoute = AiVisionRouteImport.update({
  id: '/ai-vision',
  path: '/ai-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-vision': typeof AiVisionRoute
  '/alfabyte': typeof AlfabyteRoute
  '/car-safety': typeof CarSafetyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-vision': typeof AiVisionRoute
  '/alfabyte': typeof AlfabyteRoute
  '/car-safety': typeof CarSafetyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-vision': typeof AiVisionRoute
  '/alfabyte': typeof AlfabyteRoute
  '/car-safety': typeof CarSafetyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-vision'
    | '/alfabyte'
    | '/car-safety'
    | '/robots.txt'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-vision'
    | '/alfabyte'
    | '/car-safety'
    | '/robots.txt'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/ai-vision'
    | '/alfabyte'
    | '/car-safety'
    | '/robots.txt'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiVisionRoute: typeof AiVisionRoute
  AlfabyteRoute: typeof AlfabyteRoute
  CarSafetyRoute: typeof CarSafetyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-safety': {
      id: '/car-safety'
      path: '/car-safety'
      fullPath: '/car-safety'
      preLoaderRoute: typeof CarSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alfabyte': {
      id: '/alfabyte'
      path: '/alfabyte'
      fullPath: '/alfabyte'
      preLoaderRoute: typeof AlfabyteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-vision': {
      id: '/ai-vision'
      path: '/ai-vision'
      fullPath: '/ai-vision'
      preLoaderRoute: typeof AiVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiVisionRoute: AiVisionRoute,
  AlfabyteRoute: AlfabyteRoute,
  CarSafetyRoute: CarSafetyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
